insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (1, 67, 'R',113, 16, 62, 'vs Poland (GS)');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (2, 80, 'AA',275, 27, 88, 'vs South Korea (GS)');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (3, 37, 'AA',533, 33, 24, 'vs Spain (R16)');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (4, 41, 'A',646, 27, 20, 'vs Switzerland (R16)');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (5, 14, 'A',8, 39, 72, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (6, 7, 'A',102, 16, 68, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (7, 13, 'A',677, 9, 67, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (8, 36, 'AA',88, 9, 24, 'vs Belgium (QF)');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (9, 68, 'AA',442, 13, 51, 'vs Tunisia (GS)');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (10, 63, 'A',409, 4, 49, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (11, 47, 'A',537, 33, 71, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (12, 90, 'A',386, 11, 97, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (13, 22, 'A',177, 37, 83, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (14, 65, 'A',364, 20, 68, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (15, 84, 'A',233, 28, 26, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (16, 47, 'AA',672, 9, 80, 'vs Sweden (R16)');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (17, 18, 'AA',653, 44, 35, 'vs England (QF)');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (18, 32, 'A',159, 23, 73, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (19, 79, 'A',9, 39, 78, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (20, 61, 'A',616, 26, 82, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (21, 70, 'AA',235, 21, 76, 'vs Uruguay (QF)');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (22, 85, 'AA',67, 13, 16, 'vs France (SF)');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (23, 49, 'A',611, 41, 81, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (24, 20, 'AA',389, 11, 82, 'vs Brazil (R16)');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (25, 58, 'R',446, 13, 62, 'vs Tunisia (GS)');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (26, 46, 'A',583, 32, 26, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (27, 5, 'A',19, 23, 60, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (28, 65, 'AA',174, 6, 54, 'vs France (GS)');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (29, 5, 'A',150, 23, 45, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (30, 88, 'A',522, 35, 37, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (31, 69, 'A',710, 29, 12, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (32, 50, 'AA',685, 9, 85, 'vs Sweden (R16)');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (33, 32, 'A',64, 13, 96, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (34, 2, 'A',143, 23, 62, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (35, 40, 'A',128, 25, 9, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (36, 44, 'A',16, 23, 20, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (37, 10, 'A',563, 1, 40, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (38, 51, 'A',302, 20, 22, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (39, 66, 'A',406, 36, 79, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (40, 70, 'A',314, 4, 48, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (41, 42, 'A',467, 21, 11, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (42, 86, 'A',31, 38, 65, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (43, 15, 'A',317, 35, 65, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (44, 51, 'A',694, 46, 49, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (45, 83, 'A',433, 39, 12, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (46, 81, 'A',493, 31, 36, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (47, 51, 'A',24, 5, 80, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (48, 25, 'A',413, 19, 3, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (49, 48, 'A',392, 36, 27, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (50, 43, 'A',140, 8, 73, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (51, 36, 'A',639, 3, 53, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (52, 48, 'A',132, 10, 84, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (53, 19, 'A',125, 42, 9, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (54, 52, 'A',513, 35, 44, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (55, 32, 'A',695, 46, 36, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (56, 15, 'A',658, 12, 60, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (57, 39, 'A',156, 23, 13, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (58, 62, 'A',75, 25, 82, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (59, 42, 'A',408, 36, 1, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (60, 50, 'A',449, 13, 73, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (61, 47, 'A',49, 13, 19, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (62, 16, 'A',166, 6, 91, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (63, 44, 'A',304, 20, 41, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (64, 7, 'A',649, 27, 15, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (65, 49, 'A',195, 34, 36, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (66, 6, 'A',510, 3, 68, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (67, 48, 'A',285, 40, 37, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (68, 46, 'A',204, 34, 35, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (69, 29, 'A',380, 44, 93, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (70, 67, 'A',117, 42, 66, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (71, 51, 'A',453, 13, 18, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (72, 65, 'A',532, 1, 31, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (73, 43, 'A',451, 46, 23, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (74, 16, 'A',485, 31, 77, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (75, 32, 'A',509, 21, 61, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (76, 20, 'A',576, 15, 47, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (77, 84, 'A',133, 10, 13, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (78, 55, 'A',303, 35, 32, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (79, 39, 'A',393, 36, 94, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (80, 19, 'A',296, 40, 77, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (81, 12, 'A',335, 32, 85, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (82, 43, 'A',207, 2, 80, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (83, 63, 'A',274, 11, 1, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (84, 4, 'A',461, 38, 19, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (85, 44, 'A',361, 12, 50, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (86, 70, 'A',420, 24, 98, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (87, 89, 'A',323, 32, 53, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (88, 8, 'A',618, 10, 21, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (89, 59, 'A',307, 4, 19, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (90, 70, 'A',37, 38, 68, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (91, 38, 'A',152, 40, 93, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (92, 82, 'A',337, 16, 86, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (93, 45, 'A',368, 12, 66, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (94, 13, 'A',503, 15, 92, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (95, 85, 'A',377, 44, 88, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (96, 73, 'A',41, 5, 73, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (97, 50, 'A',352, 43, 59, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (98, 30, 'A',346, 28, 60, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (99, 9, 'A',355, 28, 13, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (100, 48, 'A',602, 41, 37, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (101, 48, 'A',342, 47, 40, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (102, 33, 'A',18, 23, 8, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (103, 51, 'A',5, 39, 79, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (104, 11, 'A',428, 39, 95, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (105, 13, 'A',36, 38, 78, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (106, 81, 'A',606, 26, 45, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (107, 78, 'A',609, 26, 55, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (108, 30, 'A',94, 48, 64, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (109, 17, 'A',349, 43, 95, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (110, 81, 'A',192, 2, 74, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (111, 17, 'A',261, 11, 71, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (112, 14, 'A',414, 36, 68, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (113, 2, 'A',598, 32, 48, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (114, 11, 'A',74, 25, 63, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (115, 84, 'A',155, 40, 1, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (116, 42, 'A',248, 21, 5, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (117, 10, 'A',617, 10, 17, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (118, 62, 'A',519, 35, 93, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (119, 80, 'A',147, 8, 14, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (120, 62, 'A',26, 5, 98, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (121, 22, 'A',104, 16, 89, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (122, 82, 'A',45, 38, 15, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (123, 53, 'A',581, 32, 19, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (124, 73, 'A',279, 40, 93, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (125, 19, 'A',595, 15, 29, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (126, 30, 'A',679, 26, 74, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (127, 67, 'A',310, 4, 2, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (128, 72, 'A',517, 19, 22, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (129, 37, 'A',163, 22, 8, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (130, 10, 'A',360, 43, 48, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (131, 4, 'A',482, 6, 41, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (132, 75, 'A',457, 46, 72, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (133, 84, 'A',245, 5, 92, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (134, 5, 'A',198, 17, 9, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (135, 48, 'A',431, 8, 17, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (136, 40, 'A',138, 42, 3, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (137, 79, 'A',465, 38, 58, '');
insert into SANCIONES (id_sancion, minuto, tipo, id_miembro, id_partido, id_arbitro, partido_suspendido) values (138, 16, 'A',675, 42, 60, '');